name: Deploy Work Tracker Solution

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Power Platform CLI
        run: |
          npm install -g pac

      - name: Authenticate with Power Platform
        run: |
          pac auth create --url ${{ secrets.POWERPLATFORM_URL }} `
            --clientId ${{ secrets.POWERPLATFORM_CLIENT_ID }} `
            --clientSecret ${{ secrets.POWERPLATFORM_CLIENT_SECRET }} `
            --tenantId ${{ secrets.POWERPLATFORM_TENANT_ID }}

      - name: Import Solution
        run: |
          pac solution import --path ./WorkTrackerManaged.zip --publish-all
